apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-engine
  template:
    metadata:
      labels:
        app: ai-engine
    spec:
      containers:
      - name: ai-engine
        image: your-docker-registry/ai-engine:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine
spec:
  selector:
    app: ai-engine
  ports:
  - port: 5000
    targetPort: 5000
