apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine
  labels:
    app: ai-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-engine
  template:
    metadata:
      labels:
        app: ai-engine
    spec:
      containers:
      - name: ai-engine
        image: sudharsanomprakash/ai-engine:v3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine
  labels:
    app: ai-engine
spec:
  selector:
    app: ai-engine
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP
