apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-extender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-extender
  template:
    metadata:
      labels:
        app: scheduler-extender
    spec:
      containers:
        - name: extender
          image: sudharsanomprakash/scheduler-extender:v4.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-extender
spec:
  selector:
    app: scheduler-extender
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
