apiVersion: v1
kind: Service
metadata:
  name: aicoloc-extender
spec:
  selector:
    app: extender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aicoloc-extender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extender
  template:
    metadata:
      labels:
        app: extender
    spec:
      containers:
        - name: extender
          image: your-dockerhub-user/aicoloc-extender:latest
          env:
            - name: AI_ENGINE_URL
              value: "http://aicoloc-ai-engine:5000"
          ports:
            - containerPort: 8080
